trigger:
  branches:
    include:
      - main,dev

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

# ✅ Install .NET 7
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.0.400'
    installationPath: $(Agent.ToolsDirectory)/dotnet

# ✅ Set PATH to use installed version
- script: echo "##vso[task.prependpath]$(Agent.ToolsDirectory)/dotnet"
  displayName: 'Use .NET 7 SDK'

# ✅ Checkout code
- checkout: self

# ✅ Restore dependencies
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# ✅ Build
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# ✅ Test
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
    arguments: '--configuration $(buildConfiguration) --collect:"Code Coverage"'

# ✅ Publish
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

# ✅ Upload
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
