trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

# ✅ Install .NET 7 SDK
- task: UseDotNet@2
  displayName: 'Install .NET 7 SDK'
  inputs:
    packageType: 'sdk'
    version: '7.0.400'

# ✅ Checkout source code
- checkout: self
  displayName: 'Checkout code'

- task: DotNetCoreCLI@2
  displayName: 'Restore packages'
  inputs:
    command: 'restore'
    projects: 'DevOpsWebAPI/DevOpsWebAPI.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: 'DevOpsWebAPI/DevOpsWebAPI.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish project'
  inputs:
    command: 'publish'
    projects: 'DevOpsWebAPI/DevOpsWebAPI.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

# ✅ Publish artifacts
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
